source 'http://rubygems.org'

gem 'addressable'
gem 'chronic'
gem 'cucumber', '1.3.15'
gem 'encryptor'
gem 'frank-cucumber'
gem 'humanize'
gem 'i18n'
gem 'json'
gem 'nokogiri', '1.6.0'
gem 'pry'
gem 'require_all'
gem 'rest-client'
gem 'unicode'
gem 'wally'
